### PR TITLE
fix: Add validation for tags to ChocolateyPackagerValidator

### LINKED ISSUE #1313: [packagers] Chocolatey requires project tags to be non empty but jreleaser is not checking that
The `<tags></tags>` entry in the nuspec file must contain at least one tag to publish it to the repository, so jreleaser should maybe warn if that is missing.

### PR DESCRIPTION
**Pull request by SimonVerhoeven**
Fixes #1313

### Context

Adds validation for the tag list not being empty

### Checklist
- [x] [Review Contribution Guidelines](https://github.com/jreleaser/jreleaser/blob/master/CONTRIBUTING.adoc).
- [x] Make sure all contributed code can be distributed under the terms of the 
      [Apache License 2.0](https://github.com/jreleaser/jreleaser/blob/master/LICENSE), e.g. the code was written by 
      you or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Update [documentation](https://github.com/jreleaser/jreleaser.github.io) when applicable.

### CODE REVIEW

File: core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/validation/packagers/ChocolateyPackagerValidator.java [hunk 1]
```diff
@@ -250,6 +250,10 @@ public static void postValidateChocolatey(JReleaserContext context, Distribution
 
         Project project = context.getModel().getProject();
 
+        if (distribution.getTags().isEmpty()) {
+            errors.configuration(RB.$("validation_must_not_be_empty", "tags"));
```
Comment (aalmiray) [inline core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/validation/packagers/ChocolateyPackagerValidator.java:254]: Should probably be more specific with the missing property name. Please update it to "distribution.tags". Thanks.

Comment (SimonVerhoeven) [reply core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/validation/packagers/ChocolateyPackagerValidator.java]: Of course, I was a tad on the fence between the two myself.

**Comment by aalmiray** [comment]
Thanks! 😄
