### PR TITLE
fix(gradle): add support for blank gpg passphrase

### LINKED ISSUE #1883: [core] signing.passphrase must not be blank.
In a `signing {}` block like so:

```
    jreleaser {
        signing {
            setActive("ALWAYS")
            setMode("COMMAND")
        }
        ...
    }
```

I get the error:

```
[ERROR] signing.passphrase must not be blank.
```

But what if the PGP private key is not protected by a passphrase? It feels like jreleaser should not be enforcing it, should it?

### PR DESCRIPTION
**Pull request by JonasVautherin**
Fixes #1883 

### Context

GPG private keys are not always protected by a passphrase. Jreleaser should support unprotected keys.

### Testing

I tried it both with a passphrase-protected key and an unprotected key, and it works for me.

### Checklist
- [x] [Review Contribution Guidelines](https://github.com/jreleaser/jreleaser/blob/master/CONTRIBUTING.adoc).
- [x] Make sure all contributed code can be distributed under the terms of the 
      [Apache License 2.0](https://github.com/jreleaser/jreleaser/blob/master/LICENSE), e.g. the code was written by 
      you or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Update [documentation](https://github.com/jreleaser/jreleaser.github.io) when applicable.

### CODE REVIEW

File: core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/validation/signing/SigningValidator.java [hunk 1]
```diff
@@ -69,13 +69,19 @@ public static void validateSigning(JReleaserContext context, Mode mode, Errors e
...
-                cosign ? COSIGN_PASSWORD : GPG_PASSPHRASE,
-                "signing.passphrase",
-                signing.getPassphrase(),
-                errors,
-                context.isDryrun()));
+        String passphrase = checkProperty(context,
+            cosign ? COSIGN_PASSWORD : GPG_PASSPHRASE,
+            "signing.passphrase",
+            signing.getPassphrase(),
+            new Errors(),
```
Comment (JonasVautherin) [inline core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/validation/signing/SigningValidator.java:79]: I tried to minimise my changes. I pass `new Errors()` here as a way to ignore the errors (otherwise it just fails).

Comment (aalmiray) [reply core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/validation/signing/SigningValidator.java:79]: Yes, passing a new instance of `Errors` is the way to go. You could change the logic to always pass a new instance no matter what. 

Also, the warning should be already resolved from internal message resources. 

Given that the errors instance is new, if the passphrase is blank there should be a single error message. You could grab it and print it as a warning.

Comment (JonasVautherin) [reply core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/validation/signing/SigningValidator.java:79]: But if I print the error as a warning, it says this:

```
[WARN]    [validation] signing.passphrase must not be blank. Configure a value using the Gradle DSL, or define a System property jreleaser.gpg.passphrase, or define a JRELEASER_GPG_PASSPHRASE environment variable, or define a key/value pair in /home/jones/.jreleaser/config.properties with a key named JRELEASER_GPG_PASSPHRASE
```

Which works, but it feels a bit weird because `signing.passphrase` can actually be blank, right? This is why I was thinking of logging "[WARN] Passphrase is blank" instead.

Comment (aalmiray) [reply core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/validation/signing/SigningValidator.java:79]: Ok, right. Then please add a message resource for the new warning message stating that the passphrase is blank. And if one should be supplies then use the suggested env vars or sys props.

Comment (JonasVautherin) [reply core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/validation/signing/SigningValidator.java:79]: Done! What do you think? :blush:

File: api/jreleaser-resource-bundle/src/main/resources/org/jreleaser/bundle/Messages.properties [hunk 2]
```diff
@@ -160,6 +160,7 @@ signing.file.newer                   = {} is newer than {}
 signing.check.published.key          = Checking if key {} has been published
 signing.key.published                = Key {} was found as published
 signing.key.not.published            = Key {} was NOT found as published
+signing.passphrase.blank             = Passphrase is blank. In case a passphrase is needed, you can configure a value using the Gradle DSL, or define a System property {}, or define a {} environment variable, or define a key/value pair in {} with a key named {}
```
Comment (aalmiray) [inline api/jreleaser-resource-bundle/src/main/resources/org/jreleaser/bundle/Messages.properties]: The Gradle DSL is not the only one. There should be another message key in the resources file that can be used as a guide.

File: core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/validation/signing/SigningValidator.java [hunk 3]
```diff
@@ -69,13 +72,25 @@ public static void validateSigning(JReleaserContext context, Mode mode, Errors e
...
+            context.isDryrun());
```
Comment (aalmiray) [inline core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/validation/signing/SigningValidator.java]: The last parameter can be explicitly set to `false`.

**Review by aalmiray — CHANGES_REQUESTED** [review]

**Review by aalmiray — APPROVED** [review]

**Comment by aalmiray** [comment]
Thank you 😄

**Comment by JonasVautherin** [comment]
And thank you for the guidance! And I see that it's already released in early-access :tada:.

Out of curiosity, what is the process to get it to Maven Central? Just to have an idea about when I could expect to see it there?

**Comment by aalmiray** [comment]
Releases to Maven Central are posted every two months, at the end of the month, on even months. The next release is scheduled for June 30th. 

Per our release cadence https://github.com/jreleaser/jreleaser/discussions/873

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.19.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.19.0))
