### PR TITLE
fix(core): Avoid duplicate resources in Native Image by using -cp option during assemble step

### LINKED ISSUE #2094: [assemble] GraalVM Native Image created with JReleaser contains duplicate resources
### Steps to Reproduce

1. Checkout: https://github.com/jdheim/toolfetch
2. Use one of the two prepared branches:
  a. `demo/uber-jar` with UberJAR
  b. `demo/jar-with-deps` with JAR with deps
4. Run [`./build.sh --native`](https://github.com/jdheim/toolfetch/blob/main/scripts/build.sh)
5. Verify `target/toolfetch-0.0.1-linux-amd64-build-report.html`

### Expected Behaviour

GraalVM Native Image created with JReleaser does not contain duplicate resources.

#### UberJAR

For example, if I have Uber JAR created with `maven-shade-plugin`, using `-jar` option only (without `-cp` option) does not produce duplicate resources:
```shell
$ /home/dev/projects/toolfetch/target/jdks/graalvm-linux-amd64/graalvm-jdk-25.0.2/bin/native-image \
    -H:+UnlockExperimentalVMOptions \
    --enable-sbom=embed,cyclonedx,strict \
    -H:ResourceConfigurationFiles=/home/dev/projects/toolfetch/target/classes/META-INF/native-image/com.jdheim/toolfetch/resource-config-linux-amd64.json \
    --emit=build-report=/home/dev/projects/toolfetch/target/toolfetch-0.0.1-linux-amd64-build-report-only-jar.html \
    -jar /home/dev/projects/toolfetch/target/toolfetch-0.0.1.jar \
    -H:Name=toolfetch-0.0.1-linux-amd64
```

Image

Build Report (committed on `demo/uber-jar` branch, because I could not upload it directly in this issue):
- https://github.com/jdheim/toolfetch/blob/demo/uber-jar/toolfetch-0.0.1-linux-amd64-build-report-uber-jar-manual.html

I am producing ToolFetch CLI with [PicoCLI](https://picocli.info/) and [Logback](https://logback.qos.ch/) Logging Framework is happy when there is one `logback.xml` file packed into GraalVM Native Image:

```shell
$ toolfetch -c "/home/dev/projects/toolfetch/src/test/resources/config/happy/toolfetch_only-mandatory-fields.yaml"
[INFO] > Install kitty...
[INFO] Create /tmp/kitty
[INFO] Download https://github.com/kovidgoyal/kitty/releases/download/v0.44.0/kitty-0.44.0-x86_64.txz to /tmp/kitty/kitty-0.44.0-x86_64.txz
[INFO] Extract /tmp/kitty/kitty-0.44.0-x86_64.txz to /tmp/kitty
[INFO] Removing /tmp/kitty/kitty-0.44.0-x86_64.txz
[INFO] > Install firefox...
[INFO] Create /tmp/firefox
[INFO] Download https://ftp.mozilla.org/pub/firefox/releases/146.0.1/linux-x86_64/en-US/firefox-146.0.1.tar.xz to /tmp/firefox/firefox-146.0.1.tar.xz
[INFO] Extract /tmp/firefox/firefox-146.0.1.tar.xz to /tmp/firefox
[INFO] Removing /tmp/firefox/firefox-146.0.1.tar.xz
```

#### JAR with Dependencies

For example, if I have JAR with dependencies, using `-jar` option with `-cp` option but **without** `toolfetch-0.0.1.jar` on classpath does not produce duplicate resources:
```shell
$ /home/dev/projects/toolfetch/target/jdks/graalvm-linux-amd64/graalvm-jdk-25.0.2/bin/native-image \
    -H:+UnlockExperimentalVMOptions \
    --enable-sbom=embed,cyclonedx,strict \
    -H:ResourceConfigurationFiles=/home/dev/projects/toolfetch/target/classes/META-INF/native-image/com.jdheim/toolfetch/resource-config-linux-amd64.json \
    --emit=build-report=/home/dev/projects/toolfetch/target/toolfetch-0.0.1-linux-amd64-build-report.html \
    -jar /home/dev/projects/toolfetch/target/toolfetch-0.0.1.jar \
    -cp jars/universal/jackson-core-3.1.0.jar:jars/universal/commons-codec-1.19.0.jar:jars/universal/jansi-2.4.2.jar:jars/universal/zstd-jni-1.5.7-7.jar:jars/universal/slf4j-api-2.0.17.jar:jars/universal/itu-1.14.0.jar:jars/universal/json-schema-validator-3.0.1.jar:jars/universal/logback-core-1.5.32.jar:jars/universal/picocli-4.7.7.jar:jars/universal/logback-classic-1.5.32.jar:jars/universal/xz-1.12.jar:jars/universal/commons-lang3-3.20.0.jar:jars/universal/commons-compress-1.28.0.jar:jars/universal/jackson-annotations-2.21.jar:jars/universal/jackson-databind-3.1.0.jar:jars/universal/snakeyaml-engine-3.0.1.jar:jars/universal/dec-0.1.2.jar:jars/universal/commons-io-2.21.0.jar:jars/universal/jspecify-1.0.0.jar \
    -H:Name=toolfetch-0.0.1-linux-amd64
```

Image

Build Report (committed on `demo/jar-with-deps` branch, because I could not upload it directly in this issue):
- https://github.com/jdheim/toolfetch/blob/demo/jar-with-deps/toolfetch-0.0.1-linux-amd64-build-report-jar-with-deps-manual.html

I am producing ToolFetch CLI with [PicoCLI](https://picocli.info/) and [Logback](https://logback.qos.ch/) Logging Framework is happy when there is one `logback.xml` file packed into GraalVM Native Image:

```shell
$ toolfetch -c "/home/dev/projects/toolfetch/src/test/resources/config/happy/toolfetch_only-mandatory-fields.yaml"
[INFO] > Install kitty...
[INFO] Create /tmp/kitty
[INFO] Download https://github.com/kovidgoyal/kitty/releases/download/v0.44.0/kitty-0.44.0-x86_64.txz to /tmp/kitty/kitty-0.44.0-x86_64.txz
[INFO] Extract /tmp/kitty/kitty-0.44.0-x86_64.txz to /tmp/kitty
[INFO] Removing /tmp/kitty/kitty-0.44.0-x86_64.txz
[INFO] > Install firefox...
[INFO] Create /tmp/firefox
[INFO] Download https://ftp.mozilla.org/pub/firefox/releases/146.0.1/linux-x86_64/en-US/firefox-146.0.1.tar.xz to /tmp/firefox/firefox-146.0.1.tar.xz
[INFO] Extract /tmp/firefox/firefox-146.0.1.tar.xz to /tmp/firefox
[INFO] Removing /tmp/firefox/firefox-146.0.1.tar.xz
```

### Actual Behaviour

GraalVM Native Image created with JReleaser contains duplicate resources. [Logback](https://logback.qos.ch/) Logging Framework complains when there are two `logback.xml` files packed into GraalVM Native Image.

#### UberJAR

For example, if I have Uber JAR created with `maven-shade-plugin`:

```yaml
assemble:
  nativeImage:
    toolfetch_binary:
      executable: '{{projectName}}-{{projectVersion}}'
      archiving:
        enabled: false
      graalJdks:
        - path: '{{baseOutputDirectory}}/jdks/graalvm-linux-amd64/{{graalVmDir}}'
          platform: 'linux-x86_64'
        - path: '{{baseOutputDirectory}}/jdks/graalvm-linux-arm64/{{graalVmDir}}'
          platform: 'linux-aarch_64'
      args:
        - '-H:+UnlockExperimentalVMOptions'
        - '--enable-sbom=embed,cyclonedx,strict'
        - '-H:ResourceConfigurationFiles={{baseOutputDirectory}}/classes/META-INF/native-image/com.jdheim/toolfetch/resource-config-{{osPlatformReplaced}}.json'
        - '--emit=build-report={{baseOutputDirectory}}/{{projectName}}-{{projectVersion}}-{{osPlatformReplaced}}-build-report.html'
      mainJar:
        path: '{{baseOutputDirectory}}/{{projectName}}-{{projectVersionNumber}}.jar'
      java:
        mainClass: 'com.jdheim.{{projectName}}.Main'
```

JReleaser produces both: `-jar` option and `-cp` option which produce duplicate resources:

```shell
$ /home/dev/projects/toolfetch/target/jdks/graalvm-linux-amd64/graalvm-jdk-25.0.2/bin/native-image \
    -H:+UnlockExperimentalVMOptions \
    --enable-sbom=embed,cyclonedx,strict \
    -H:ResourceConfigurationFiles=/home/dev/projects/toolfetch/target/classes/META-INF/native-image/com.jdheim/toolfetch/resource-config-linux-amd64.json \
    --emit=build-report=/home/dev/projects/toolfetch/target/toolfetch-0.0.1-linux-amd64-build-report.html \
    -jar /home/dev/projects/toolfetch/target/toolfetch-0.0.1.jar \
    -cp jars/universal/toolfetch-0.0.1.jar \
    -H:Name=toolfetch-0.0.1-linux-amd64
```

Image

Build Report (committed on `demo/uber-jar` branch, because I could not upload it directly in this issue):
- https://github.com/jdheim/toolfetch/blob/demo/uber-jar/toolfetch-0.0.1-linux-amd64-build-report-uber-jar-jreleaser.html

Trace log:
- [trace-uber-jar-jreleaser.log](https://github.com/user-attachments/files/26309074/trace-uber-jar-jreleaser.log)

I am producing ToolFetch CLI with [PicoCLI](https://picocli.info/) and [Logback](https://logback.qos.ch/) Logging Framework is not happy about two `logback.xml` files packed into GraalVM Native Image. Logback warns that there are two `logback.xml` files on each CLI run:

```shell
$ toolfetch -c "/home/dev/projects/toolfetch/src/test/resources/config/happy/toolfetch_only-mandatory-fields.yaml"
18:52:39,456 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found logback-core version 1.5.32
18:52:39,456 |-INFO in ch.qos.logback.classic.util.ContextInitializer@76ced70d - No custom configurators were discovered as a service.
18:52:39,456 |-INFO in ch.qos.logback.classic.util.ContextInitializer@76ced70d - Trying to configure with ch.qos.logback.classic.util.DefaultJoranConfigurator
18:52:39,456 |-INFO in ch.qos.logback.classic.util.ContextInitializer@76ced70d - Constructed configurator of type class ch.qos.logback.classic.util.DefaultJoranConfigurator
18:52:39,456 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
18:52:39,456 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [resource:/logback.xml]
18:52:39,456 |-WARN in ch.qos.logback.classic.util.DefaultJoranConfigurator@1e2e0229 - Resource [logback.xml] occurs multiple times on the classpath.
18:52:39,456 |-WARN in ch.qos.logback.classic.util.DefaultJoranConfigurator@1e2e0229 - Resource [logback.xml] occurs at [resource:/logback.xml#1]
18:52:39,456 |-WARN in ch.qos.logback.classic.util.DefaultJoranConfigurator@1e2e0229 - Resource [logback.xml] occurs at [resource:/logback.xml]
18:52:39,457 |-INFO in ch.qos.logback.classic.model.processor.ConfigurationModelHandlerFull - Scan attribute not set or set to unrecognized value.
18:52:39,457 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [CONSOLE]
18:52:39,457 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
18:52:39,457 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
18:52:39,457 |-INFO in ch.qos.logback.core.ConsoleAppender[CONSOLE] - NOTE: Writing to the console can be slow. Try to avoid logging to the 
18:52:39,457 |-INFO in ch.qos.logback.core.ConsoleAppender[CONSOLE] - console in production environments, especially in high volume systems.
18:52:39,457 |-INFO in ch.qos.logback.core.ConsoleAppender[CONSOLE] - See also https://logback.qos.ch/codes.html#slowConsole
18:52:39,457 |-INFO in ch.qos.logback.core.ConsoleAppender[CONSOLE] - Enabling JANSI AnsiPrintStream for the console.
18:52:39,459 |-INFO in ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to INFO
18:52:39,459 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [CONSOLE] to Logger[ROOT]
18:52:39,459 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@b3b3913 - End of configuration.
18:52:39,459 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@19ebe7ba - Registering current configuration as safe fallback point
18:52:39,459 |-INFO in ch.qos.logback.classic.util.ContextInitializer@76ced70d - ch.qos.logback.classic.util.DefaultJoranConfigurator.configure() call lasted 3 milliseconds. ExecutionStatus=DO_NOT_INVOKE_NEXT_IF_ANY

[INFO] > Install kitty...
[INFO] Create /tmp/kitty
[INFO] Download https://github.com/kovidgoyal/kitty/releases/download/v0.44.0/kitty-0.44.0-x86_64.txz to /tmp/kitty/kitty-0.44.0-x86_64.txz
[INFO] Extract /tmp/kitty/kitty-0.44.0-x86_64.txz to /tmp/kitty
[INFO] Removing /tmp/kitty/kitty-0.44.0-x86_64.txz
[INFO] > Install firefox...
[INFO] Create /tmp/firefox
[INFO] Download https://ftp.mozilla.org/pub/firefox/releases/146.0.1/linux-x86_64/en-US/firefox-146.0.1.tar.xz to /tmp/firefox/firefox-146.0.1.tar.xz
[INFO] Extract /tmp/firefox/firefox-146.0.1.tar.xz to /tmp/firefox
[INFO] Removing /tmp/firefox/firefox-146.0.1.tar.xz
```

#### JAR with dependencies

For example, if I have JAR with dependencies:

```yaml
assemble:
  nativeImage:
    toolfetch_binary:
      executable: '{{projectName}}-{{projectVersion}}'
      archiving:
        enabled: false
      graalJdks:
        - path: '{{baseOutputDirectory}}/jdks/graalvm-linux-amd64/{{graalVmDir}}'
          platform: 'linux-x86_64'
        - path: '{{baseOutputDirectory}}/jdks/graalvm-linux-arm64/{{graalVmDir}}'
          platform: 'linux-aarch_64'
      args:
        - '-H:+UnlockExperimentalVMOptions'
        - '--enable-sbom=embed,cyclonedx,strict'
        - '-H:ResourceConfigurationFiles={{baseOutputDirectory}}/classes/META-INF/native-image/com.jdheim/toolfetch/resource-config-{{osPlatformReplaced}}.json'
        - '--emit=build-report={{baseOutputDirectory}}/{{projectName}}-{{projectVersion}}-{{osPlatformReplaced}}-build-report.html'
      mainJar:
        path: '{{baseOutputDirectory}}/{{projectName}}-{{projectVersionNumber}}.jar'
      jars:
        - pattern: '{{baseOutputDirectory}}/third-party/lib/*.jar'
      java:
        mainClass: 'com.jdheim.{{projectName}}.Main'
```

Notice that there is no `toolfetch-0.0.1.jar` in `{{baseOutputDirectory}}/third-party/lib/*.jar`:

```shell
.
|-- commons-codec-1.19.0.jar
|-- commons-compress-1.28.0.jar
|-- commons-io-2.21.0.jar
|-- commons-lang3-3.20.0.jar
|-- dec-0.1.2.jar
|-- itu-1.14.0.jar
|-- jackson-annotations-2.21.jar
|-- jackson-core-3.1.0.jar
|-- jackson-databind-3.1.0.jar
|-- jansi-2.4.2.jar
|-- json-schema-validator-3.0.1.jar
|-- jspecify-1.0.0.jar
|-- logback-classic-1.5.32.jar
|-- logback-core-1.5.32.jar
|-- picocli-4.7.7.jar
|-- slf4j-api-2.0.17.jar
|-- snakeyaml-engine-3.0.1.jar
|-- xz-1.12.jar
`-- zstd-jni-1.5.7-7.jar

1 directory, 19 files
```

JReleaser produces `-jar` option with `-cp` option and also **with** `toolfetch-0.0.1.jar` on classpath which produce duplicate resources:

```shell
$ /home/dev/projects/toolfetch/target/jdks/graalvm-linux-amd64/graalvm-jdk-25.0.2/bin/native-image \
    -H:+UnlockExperimentalVMOptions \
    --enable-sbom=embed,cyclonedx,strict \
    -H:ResourceConfigurationFiles=/home/dev/projects/toolfetch/target/classes/META-INF/native-image/com.jdheim/toolfetch/resource-config-linux-amd64.json \
    --emit=build-report=/home/dev/projects/toolfetch/target/toolfetch-0.0.1-linux-amd64-build-report.html \
    -jar /home/dev/projects/toolfetch/target/toolfetch-0.0.1.jar \
    -cp jars/universal/toolfetch-0.0.1.jar:jars/universal/jackson-core-3.1.0.jar:jars/universal/commons-codec-1.19.0.jar:jars/universal/jansi-2.4.2.jar:jars/universal/zstd-jni-1.5.7-7.jar:jars/universal/slf4j-api-2.0.17.jar:jars/universal/itu-1.14.0.jar:jars/universal/json-schema-validator-3.0.1.jar:jars/universal/logback-core-1.5.32.jar:jars/universal/picocli-4.7.7.jar:jars/universal/logback-classic-1.5.32.jar:jars/universal/xz-1.12.jar:jars/universal/commons-lang3-3.20.0.jar:jars/universal/commons-compress-1.28.0.jar:jars/universal/jackson-annotations-2.21.jar:jars/universal/jackson-databind-3.1.0.jar:jars/universal/snakeyaml-engine-3.0.1.jar:jars/universal/dec-0.1.2.jar:jars/universal/commons-io-2.21.0.jar:jars/universal/jspecify-1.0.0.jar \
    -H:Name=toolfetch-0.0.1-linux-amd64
```

Image

Build Report (committed on `demo/jar-with-deps` branch, because I could not upload it directly in this issue):
- https://github.com/jdheim/toolfetch/blob/demo/jar-with-deps/toolfetch-0.0.1-linux-amd64-build-report-jar-with-deps-jreleaser.html

Trace log:
- [trace-jar-with-deps-jreleaser.log](https://github.com/user-attachments/files/26309080/trace-jar-with-deps-jreleaser.log)

I am producing ToolFetch CLI with [PicoCLI](https://picocli.info/) and [Logback](https://logback.qos.ch/) Logging Framework is not happy about two `logback.xml` files packed into GraalVM Native Image. Logback warns that there are two `logback.xml` files on each CLI run:

```shell
$ toolfetch -c "/home/dev/projects/toolfetch/src/test/resources/config/happy/toolfetch_only-mandatory-fields.yaml"
19:45:48,513 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found logback-core version 1.5.32
19:45:48,513 |-INFO in ch.qos.logback.classic.util.ContextInitializer@f48aaeb - No custom configurators were discovered as a service.
19:45:48,513 |-INFO in ch.qos.logback.classic.util.ContextInitializer@f48aaeb - Trying to configure with ch.qos.logback.classic.util.DefaultJoranConfigurator
19:45:48,513 |-INFO in ch.qos.logback.classic.util.ContextInitializer@f48aaeb - Constructed configurator of type class ch.qos.logback.classic.util.DefaultJoranConfigurator
19:45:48,513 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
19:45:48,513 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [resource:/logback.xml]
19:45:48,513 |-WARN in ch.qos.logback.classic.util.DefaultJoranConfigurator@3a42f8c8 - Resource [logback.xml] occurs multiple times on the classpath.
19:45:48,513 |-WARN in ch.qos.logback.classic.util.DefaultJoranConfigurator@3a42f8c8 - Resource [logback.xml] occurs at [resource:/logback.xml#1]
19:45:48,513 |-WARN in ch.qos.logback.classic.util.DefaultJoranConfigurator@3a42f8c8 - Resource [logback.xml] occurs at [resource:/logback.xml]
19:45:48,514 |-INFO in ch.qos.logback.classic.model.processor.ConfigurationModelHandlerFull - Scan attribute not set or set to unrecognized value.
19:45:48,514 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [CONSOLE]
19:45:48,514 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
19:45:48,514 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
19:45:48,514 |-INFO in ch.qos.logback.core.ConsoleAppender[CONSOLE] - NOTE: Writing to the console can be slow. Try to avoid logging to the 
19:45:48,514 |-INFO in ch.qos.logback.core.ConsoleAppender[CONSOLE] - console in production environments, especially in high volume systems.
19:45:48,514 |-INFO in ch.qos.logback.core.ConsoleAppender[CONSOLE] - See also https://logback.qos.ch/codes.html#slowConsole
19:45:48,514 |-INFO in ch.qos.logback.core.ConsoleAppender[CONSOLE] - Enabling JANSI AnsiPrintStream for the console.
19:45:48,519 |-INFO in ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to INFO
19:45:48,519 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [CONSOLE] to Logger[ROOT]
19:45:48,519 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@16521efb - End of configuration.
19:45:48,519 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@51732947 - Registering current configuration as safe fallback point
19:45:48,519 |-INFO in ch.qos.logback.classic.util.ContextInitializer@f48aaeb - ch.qos.logback.classic.util.DefaultJoranConfigurator.configure() call lasted 6 milliseconds. ExecutionStatus=DO_NOT_INVOKE_NEXT_IF_ANY

[INFO] > Install kitty...
[INFO] Create /tmp/kitty
[INFO] Download https://github.com/kovidgoyal/kitty/releases/download/v0.44.0/kitty-0.44.0-x86_64.txz to /tmp/kitty/kitty-0.44.0-x86_64.txz
[INFO] Extract /tmp/kitty/kitty-0.44.0-x86_64.txz to /tmp/kitty
[INFO] Removing /tmp/kitty/kitty-0.44.0-x86_64.txz
[INFO] > Install firefox...
[INFO] Create /tmp/firefox
[INFO] Download https://ftp.mozilla.org/pub/firefox/releases/146.0.1/linux-x86_64/en-US/firefox-146.0.1.tar.xz to /tmp/firefox/firefox-146.0.1.tar.xz
[INFO] Extract /tmp/firefox/firefox-146.0.1.tar.xz to /tmp/firefox
[INFO] Removing /tmp/firefox/firefox-146.0.1.tar.xz
```

### Environment Information

- **Operating System**: Ubuntu 25.10, x86_64
- **JReleaser Version:** 1.23.0
- **JDK Version:** 25.0.2

### PR DESCRIPTION
**Pull request by p-marcin**
Fixes #2094

### Context

Before the changes in this PR, JReleaser was using both: `-jar` and `-cp` options during Native Image assemble step.
Using both options results in duplicate resources in Native Image as shown in #2094.

The official [Native Maven Plugin](https://graalvm.github.io/native-build-tools/latest/maven-plugin.html) is using `-cp` option without `-jar` option and with main class at the end of the command.

The proposed solution is using `-cp` option with main class at the end of the command.
In `native-image` command when `-cp` option is used, main class at the end of the command is mandatory.
If user does not specify main class in `jreleaser.yml` (optional):
- In case of `-cp`: try to autodetect main class in Main Jar Manifest
- In case of `-jar`: `native-image` command autodetects main class in Main Jar Manifest

Changes were tested on real setup. Attaching the logs for Uber JAR case:
[trace-uber-jar-fix.log](https://github.com/user-attachments/files/26169625/trace-uber-jar-fix.log)

[Build Report](https://github.com/jdheim/toolfetch/blob/demo/uber-jar/toolfetch-0.0.1-linux-amd64-build-report-uber-jar-fix.html) indicates no duplicate resources:
uber-jar-fix

Attaching the logs for JAR with dependencies case:
[trace-jar-with-deps-fix.log](https://github.com/user-attachments/files/26169656/trace-jar-with-deps-fix.log)

[Build Report](https://github.com/jdheim/toolfetch/blob/demo/jar-with-deps/toolfetch-0.0.1-linux-amd64-build-report-jar-with-deps-fix.html) indicates no duplicate resources:
jar-with-deps-fix

The changes were also covered with JUnit Tests.

#### UberJAR

Before this PR the command looked like:

```shell
$ /tmp/junit-6453018531140388171/graalvm-jdk/bin/native-image \
    -jar \
    /tmp/junit-6453018531140388171/jreleaser-1.24.0.jar \
    -cp \
    jars/universal/jreleaser-1.24.0.jar \
    -H:Name=jreleaser-1.24.0-linux-amd64
```

After the changes in this PR the command looks like:

```shell
$ /tmp/junit-6453018531140388171/graalvm-jdk/bin/native-image \
    -cp \
    jars/universal/jreleaser-1.24.0.jar \
    -H:Name=jreleaser-1.24.0-linux-amd64 \
    org.jreleaser.cli.Main
```

#### JAR with dependencies

Before this PR the command looked like:

```shell
$ /tmp/junit-1579422173321533875/graalvm-jdk/bin/native-image \
    -jar \
    /tmp/junit-1579422173321533875/jreleaser-1.24.0.jar \
    -cp \
    jars/universal/jreleaser-1.24.0.jar:jars/universal/dependency1-1.0.0.jar:jars/universal/dependency2-2.0.0.jar:jars/universal/dependency3-3.0.0.jar \
    -H:Name=jreleaser-1.24.0-linux-amd64
```

After the changes in this PR the command looks like:

```shell
$ /tmp/junit-1579422173321533875/graalvm-jdk/bin/native-image \
    -cp \
    jars/universal/jreleaser-1.24.0.jar:jars/universal/dependency1-1.0.0.jar:jars/universal/dependency2-2.0.0.jar:jars/universal/dependency3-3.0.0.jar \
    -H:Name=jreleaser-1.24.0-linux-amd64 \
    org.jreleaser.cli.Main
```

### Modular App

No regressions when testing modular app:

image

image

[trace.log](https://github.com/user-attachments/files/26227633/trace.log)

### Checklist
- [x] [Review Contribution Guidelines](https://github.com/jreleaser/jreleaser/blob/master/CONTRIBUTING.adoc).
- [x] Make sure all contributed code can be distributed under the terms of the 
      [Apache License 2.0](https://github.com/jreleaser/jreleaser/blob/master/LICENSE), e.g. the code was written by 
      you or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Update [documentation](https://github.com/jreleaser/jreleaser.github.io) when applicable.

### CODE REVIEW

File: core/jreleaser-engine/src/test/java/org/jreleaser/assemblers/NativeImageAssemblerProcessorTest.java [hunk 1]
```diff
@@ -0,0 +1,366 @@
...
+        Artifact graal = mock(Artifact.class);
+
+        when(graal.isActiveAndSelected()).thenReturn(true);
+        when(graal.getEffectivePath(any(JReleaserContext.class), any(Assembler.class))).thenReturn(graalVmJdkDir);
+        when(graal.getPlatform()).thenReturn(DETECTED_OS_ARCH);
+
+        return graal;
+    }
+
+    private void mockPlatform() {
```
Comment (aalmiray) [inline core/jreleaser-engine/src/test/java/org/jreleaser/assemblers/NativeImageAssemblerProcessorTest.java]: Why are these replacements needed?

File: core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/NativeImageAssemblerProcessor.java [hunk 2]
```diff
@@ -205,10 +207,21 @@ private void nativeImage(TemplateContext props, Path assembleDirectory, Path gra
                         .map(Path::toString)
                         .map(this::maybeQuote)
                         .collect(joining(File.pathSeparator)));
+            } else {
```
Comment (aalmiray) [inline core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/NativeImageAssemblerProcessor.java]: The `jars` variable should contain at least the main jar, shouldn't it? In which case this branch will never be executed.

File: core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/NativeImageAssemblerProcessor.java [hunk 3]
```diff
@@ -205,10 +207,21 @@ private void nativeImage(TemplateContext props, Path assembleDirectory, Path gra
...
+                cmd.arg("-jar")
+                    .arg(maybeQuote(assembler.getMainJar().getEffectivePath(context, assembler).toAbsolutePath().toString()));
             }
         }
 
         cmd.arg("-H:Name=" + executable);
+        if (isBlank(assembler.getJava().getMainModule()) && !jars.isEmpty()) {
```
Comment (aalmiray) [inline core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/NativeImageAssemblerProcessor.java]: The mainClass may be set even if the mainModule isn't, which is the case when the app is non-modular. This condition should check only for the mainClass' presence.

Or put it in the other way, the code should be able to handle resolution of the main class for both types of apps: non-modular (what's in this PR so far) and modular (appears to be missing).

File: core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/NativeImageAssemblerProcessor.java (hunk 2 above)
Comment (p-marcin) [reply core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/NativeImageAssemblerProcessor.java]: Yes, indeed. I was not sure if I should leave it in case of some future changes which could trigger this branch. But it can be removed as well. I will remove this branch then.

File: core/jreleaser-engine/src/test/java/org/jreleaser/assemblers/NativeImageAssemblerProcessorTest.java (hunk 1 above)
Comment (p-marcin) [reply core/jreleaser-engine/src/test/java/org/jreleaser/assemblers/NativeImageAssemblerProcessorTest.java]: I am using these replacements in my `jreleaser.yml`. However, they are not mandatory. I will remove them.

File: core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/NativeImageAssemblerProcessor.java (hunk 3 above)
Comment (p-marcin) [reply core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/NativeImageAssemblerProcessor.java]: I don't use modules at all and the Issue was raised only for non-modular apps.

Hence, I made sure there are no regressions (created missing JUnit Tests).

> Or put it in the other way, the code should be able to handle resolution of the main class for both types of apps

However, shouldn't this be enough?
https://github.com/jreleaser/jreleaser/blob/39250fa7f3feb72aa88e270f138227d86590212e/core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/NativeImageAssemblerProcessor.java#L184-L185

Which resolves to:
```shell
$ /tmp/junit-1214896182389707713/graalvm-jdk/bin/native-image \
      --module \
      org.jreleaser.cli/org.jreleaser.cli.Main \
      --module-path \
      /tmp/junit-1214896182389707713/jreleaser/assemble/jreleaser-native/native-image/jars/universal \
      -H:Name=jreleaser-1.24.0-linux-amd64
```

Or do you mean auto detect of Main Class should also work for modular apps?

Comment (p-marcin) [reply core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/NativeImageAssemblerProcessor.java]: Or, do you mean `--module` should be last?

Example:
```shell
$ /tmp/junit-1214896182389707713/graalvm-jdk/bin/native-image \
      --module-path \
      /tmp/junit-1214896182389707713/jreleaser/assemble/jreleaser-native/native-image/jars/universal \
      -H:Name=jreleaser-1.24.0-linux-amd64 \
      --module \
      org.jreleaser.cli/org.jreleaser.cli.Main
```

Comment (p-marcin) [reply core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/NativeImageAssemblerProcessor.java]: I've made some changes. Please let me know if they're acceptable.

File: core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/NativeImageAssemblerProcessor.java [hunk 4]
```diff
@@ -194,21 +196,26 @@ private void nativeImage(TemplateContext props, Path assembleDirectory, Path gra
...
 
         cmd.arg("-H:Name=" + executable);
+        String mainClass = assembler.getJava().getMainClass();
+        if (isBlank(mainClass)) {
+            mainClass = tryAutoDetectMainClass();
+        }
+        if (isNotBlank(assembler.getJava().getMainModule())) {
+            cmd.arg("--module")
+                .arg(resolveTemplate(context.getLogger(), assembler.getJava().getMainModule(), props) + "/" + resolveTemplate(context.getLogger(), mainClass, props));
+        } else if (isNotBlank(mainClass)) {
```
Comment (aalmiray) [inline core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/NativeImageAssemblerProcessor.java]: What happens if mainClass is null? Should the processor fail explicitly?

Comment (p-marcin) [reply core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/NativeImageAssemblerProcessor.java]: This case is handled by `native-image` command.

Before my changes there was:
```shell
[ERROR]     [native-image] Error: No main manifest attribute, in /home/dev/projects/toolfetch/target/toolfetch-0.0.1.jar
```

After my changes there is
```shell
[ERROR]     [native-image] Error: Please specify class (or <module>/<mainclass>) containing the main entry point method. (see --help)
```

Comment (p-marcin) [reply core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/NativeImageAssemblerProcessor.java]: I committed a new change with new Error Message:
image

What do you think?

File: core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/NativeImageAssemblerProcessor.java [hunk 5]
```diff
@@ -194,21 +197,27 @@ private void nativeImage(TemplateContext props, Path assembleDirectory, Path gra
...
+                .arg(jars.stream()
+                    .map(Path::toAbsolutePath)
+                    .map(image.getParent()::relativize)
+                    .map(Path::toString)
+                    .map(this::maybeQuote)
+                    .collect(joining(File.pathSeparator)));
         }
 
         cmd.arg("-H:Name=" + executable);
+        String mainClass = Optional.ofNullable(assembler.getJava().getMainClass())
```
Comment (aalmiray) [inline core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/NativeImageAssemblerProcessor.java]: This could a simple if/else or a ternary operator ?:

The use of Optional in this case is too much IMHO. 

The use Optional.ofNullable() in the additional method that searches for a manifest entry otoh is barely acceptable due to chained usages of the map() method. However, in this case there's only two branches.

Comment (p-marcin) [reply core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/NativeImageAssemblerProcessor.java]: Processed review remarks

File: api/jreleaser-resource-bundle/src/main/resources/org/jreleaser/bundle/Messages.properties [hunk 6]
```diff
@@ -340,6 +340,7 @@ ERROR_jpackage_runtime_image_not_found     = Could not find a runtime image matc
 ERROR_swid_generator                       = Unexpected error when generating SWID tag from {}
 ERROR_assemble_swid_tag                    = Unexpected error when generating SWID tag for {}
 assemble.deb.unsupported.artifact          = Deb assembler does not support artifact for {}
+ERROR_assembler_no_main_class              = Could not resolve main class: not configured and no Main-Class found in manifest of {}
```
Comment (aalmiray) [inline api/jreleaser-resource-bundle/src/main/resources/org/jreleaser/bundle/Messages.properties]: Please update to "Could not resolve main class: value not configured in the DSL and no Main-Class attribute found in the manifest of {}"

File: core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/NativeImageAssemblerProcessor.java [hunk 7]
```diff
@@ -248,6 +252,14 @@ private void nativeImage(TemplateContext props, Path assembleDirectory, Path gra
         }
     }
 
+    private String tryAutoDetectMainClass() {
+        try (JarFile mainJar = new JarFile(assembler.getMainJar().getEffectivePath(context, assembler).toString())) {
+            return mainJar.getManifest().getMainAttributes().getValue(Attributes.Name.MAIN_CLASS);
+        } catch (Exception ignored) {
+            return "";
```
Comment (aalmiray) [inline core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/NativeImageAssemblerProcessor.java:260]: Please log the exception in `debug` level.

File: api/jreleaser-resource-bundle/src/main/resources/org/jreleaser/bundle/Messages.properties (hunk 6 above)
Comment (p-marcin) [reply api/jreleaser-resource-bundle/src/main/resources/org/jreleaser/bundle/Messages.properties]: Processed review remark

File: core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/NativeImageAssemblerProcessor.java (hunk 7 above)
Comment (p-marcin) [reply core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/NativeImageAssemblerProcessor.java:260]: Processed review remark

File: core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/NativeImageAssemblerProcessor.java [hunk 8]
```diff
@@ -194,21 +194,25 @@ private void nativeImage(TemplateContext props, Path assembleDirectory, Path gra
...
+                    .map(image.getParent()::relativize)
+                    .map(Path::toString)
+                    .map(this::maybeQuote)
+                    .collect(joining(File.pathSeparator)));
         }
 
         cmd.arg("-H:Name=" + executable);
+        String mainClass = isNotBlank(assembler.getJava().getMainClass()) ? assembler.getJava().getMainClass() : tryAutoDetectMainClass();
+        if (isBlank(mainClass)) {
+            throw new AssemblerProcessingException(RB.$("ERROR_assembler_no_main_class", assembler.getMainJar().getPath()));
```
Comment (aalmiray) [inline core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/NativeImageAssemblerProcessor.java]: `getPath()` returns the value configured in the DSL as is, while `getResolvedPath()` should provide the fully resolved value IIRC. There are two places where this update should happen in this PR.

Comment (p-marcin) [reply core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/NativeImageAssemblerProcessor.java]: Ok, indeed. I was using:
```yaml
mainJar:
  path: '{{baseOutputDirectory}}/{{projectName}}-{{projectVersionNumber}}.jar'
```
and didn't notice any difference.

Processed review remark

**Comment by aalmiray** [comment]
Thank you 😄
