### PR TITLE
fix(mavencentral): show clear error messages for 401/403 (fixes #1922)

### LINKED ISSUE #1922: [deploy] Unauthorized shouldn't be a unexpected error
i'm now on 5th attempt trying to publish new jbang since new mavencentral and yes, part of it is my own mess but also a bit tedious to get this in logs:

```
[INFO]      [mavenCentral]  - dev.jbang-jbang-0.127.4-bundle.zip
[INFO]      [mavenCentral] Uploading dev.jbang-jbang-0.127.4-bundle.zip
[INFO]  Writing output properties to out/jreleaser/output.properties
Error:  JReleaser failed after 53.340 s
Unexpected error
Unexpected error when deploying out/jreleaser/deploy/mavenCentral/jbang/dev.jbang-jbang-0.127.4-bundle.zip: Unexpected error
Error: Process completed with exit code 1.
```

to then having to download logs to locate that the "unexpected error" is quite an expectable one:

```
Caused by: jreleaser.shadow.org.jreleaser.sdk.mavencentral.api.MavenCentralAPIException: 401: Unauthorized
	at jreleaser.shadow.org.jreleaser.sdk.mavencentral.MavenCentral$MavenCentralErrorDecoder.decode(MavenCentral.java:296)
	at jreleaser.shadow.feign.InvocationContext.decodeError(InvocationContext.java:133)
	at jreleaser.shadow.feign.InvocationContext.proceed(InvocationContext.java:80)
	at jreleaser.shadow.feign.RedirectionInterceptor.intercept(RedirectionInterceptor.java:46)
	at jreleaser.shadow.feign.ResponseInterceptor.lambda$apply$2(ResponseInterceptor.java:68)
	at jreleaser.shadow.feign.ResponseHandler.handleResponse(ResponseHandler.java:69)
	at jreleaser.shadow.feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:109)
	at jreleaser.shadow.feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:53)
	at jreleaser.shadow.feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:104)
	at com.sun.proxy.$Proxy20.upload(Unknown Source)
	at jreleaser.shadow.org.jreleaser.sdk.mavencentral.MavenCentral.lambda$upload$2(MavenCentral.java:138)
	at jreleaser.shadow.org.jreleaser.sdk.mavencentral.MavenCentral.wrap(MavenCentral.java:160)
```

would be great if it could just say the error was due to unauthorized access :)

thanks!

### PR DESCRIPTION
**Pull request by ramanathan1504**
Improve error messages for 401/403 in MavenCentral deploy (Fixes #1922)

Fixes #1922

### Context
This PR improves developer experience by replacing the vague "Unexpected error" during MavenCentral deployments with clear, actionable error messages.

- For 401 Unauthorized responses:
  ❌ Unauthorized (401): Please check your Maven Central credentials or token.

- For 403 Forbidden responses:
  ❌ Forbidden (403): You don't have permission to upload to this repository.

This makes it much easier to diagnose publishing issues and removes the need to dig into logs.

### Checklist
- [x] [Review Contribution Guidelines](https://github.com/jreleaser/jreleaser/blob/master/CONTRIBUTING.adoc).
- [x] Code is original and Apache 2.0-compatible.
- [x] Unit tests added (`MavenCentralErrorDecoderTest`).
- [ ] Documentation not required for this internal change.

### CODE REVIEW

File: sdks/jreleaser-mavencentral-java-sdk/src/test/java/org/jreleaser/sdk/mavencentral/MavenCentralErrorDecoderTest.java [hunk 1]
```diff
@@ -0,0 +1,168 @@
...
+import org.jreleaser.sdk.mavencentral.api.MavenCentralAPIException;
+import org.junit.jupiter.api.Test;
+
+import feign.Request;
+import feign.RequestTemplate;
+import feign.Response;
+import feign.RetryableException;
+
+class MavenCentralErrorDecoderTest {
+    private final JReleaserLogger logger = new JReleaserLogger() {
```
Comment (aalmiray) [inline sdks/jreleaser-mavencentral-java-sdk/src/test/java/org/jreleaser/sdk/mavencentral/MavenCentralErrorDecoderTest.java]: Use `SimpleJReleaserLoggerAdapter` from the jrelease-logger-api subproject. It should already be in the project's dependencies. If not then it should be added to the `testImolementation` configuration in the build file.

File: sdks/jreleaser-mavencentral-java-sdk/src/main/java/org/jreleaser/sdk/mavencentral/MavenCentral.java [hunk 2]
```diff
@@ -299,6 +299,16 @@ public Exception decode(String methodKey, Response response) {
                     response.request());
             }
 
+            // Handle Unauthorized error
+            if (response.status() == 401) {
+                return new MavenCentralAPIException(401, "❌ Unauthorized (401): Please check your Maven Central credentials or token.", response.headers());
```
Comment (aalmiray) [inline sdks/jreleaser-mavencentral-java-sdk/src/main/java/org/jreleaser/sdk/mavencentral/MavenCentral.java]: Please use message resources instead of explicit text. Also, follow the same message patterns (no emojis).

**Review by ramanathan1504 — COMMENTED** [review]
Thank you for the review! I’ll make the suggested changes and push the update shortly.

**Review by ramanathan1504 — COMMENTED** [review]
Updated the error messages to use Messages.resolve() instead of hardcoded strings, and removed emojis.
Replaced the custom logger in the test with SimpleJReleaserLoggerAdapter from jreleaser-logger-api.

Let me know if anything else needs updating. Thanks again for the review!

**Comment by ramanathan1504** [comment]
⚠️ Apologies — auto-format applied some extra formatting to the file.
Let me know if you’d prefer I revert those to match the existing project style. Happy to update!

**Comment by aalmiray** [comment]
Yes, please. The reformatting messes up the actual changes. Would be great if you could revert it.

File: api/jreleaser-resource-bundle/src/main/resources/org/jreleaser/bundle/Messages.properties [hunk 3]
```diff
@@ -29,6 +29,9 @@ not = not
 set.to = {} set to {}
 
 ERROR_unexpected_error = Unexpected error
+ERROR_unauthorized = Unauthorized error check your Maven Central credentials or token
```
Comment (aalmiray) [inline api/jreleaser-resource-bundle/src/main/resources/org/jreleaser/bundle/Messages.properties]: Please change to

ERROR_maven_central_unauthorized = Unauthorized. Please check credentials for {}

Pass in `"deploy.maven." + mavenDeployer.getName()` as argument

File: api/jreleaser-resource-bundle/src/main/resources/org/jreleaser/bundle/Messages.properties [hunk 4]
```diff
@@ -29,6 +29,9 @@ not = not
...
+ERROR_forbidden = Forbidden error does not have permission to perform the action
```
Comment (aalmiray) [inline api/jreleaser-resource-bundle/src/main/resources/org/jreleaser/bundle/Messages.properties]: Please change to

ERROR_maven_central_forbidden = Forbidden. Operation not allowed

File: api/jreleaser-resource-bundle/src/main/resources/org/jreleaser/bundle/Messages.properties (hunk 3 above)
Comment (ramanathan1504) [reply api/jreleaser-resource-bundle/src/main/resources/org/jreleaser/bundle/Messages.properties]: •	Changed the message key to ERROR_maven_central_unauthorized
	•	Message now reads: "Unauthorized. Please check credentials for {}"
	•	Passed "deploy.maven." + mavenDeployer.getName() as the argument

File: api/jreleaser-resource-bundle/src/main/resources/org/jreleaser/bundle/Messages.properties (hunk 4 above)
Comment (ramanathan1504) [reply api/jreleaser-resource-bundle/src/main/resources/org/jreleaser/bundle/Messages.properties]: updated

**Comment by ramanathan1504** [comment]
Also revert back the auto formatted file

File: sdks/jreleaser-mavencentral-java-sdk/src/main/java/org/jreleaser/sdk/mavencentral/MavenCentral.java (hunk 2 above)
Comment (ramanathan1504) [reply sdks/jreleaser-mavencentral-java-sdk/src/main/java/org/jreleaser/sdk/mavencentral/MavenCentral.java]: revert back the auto formatted file

**Review by aalmiray — APPROVED** [review]

**Comment by aalmiray** [comment]
Thank you 😄

**Review by ramanathan1504 — COMMENTED** [review]
Thanks for the review and guidance! Excited to contribute more. 🙌

**Comment by aalmiray** [comment]
Contributions are always welcome. We've got a few issues marked for starting with the codebase.

**Comment by ramanathan1504** [comment]
Got it, thank you!
I’ll check out the issues marked for starting with the codebase and pick one to work on.
Really appreciate the guidance!
