### PR TITLE
fix(core): Fix "Cannot parse CALVER version" with 0Y.0M.MICRO/YY.0M.MICRO

### LINKED ISSUE #1728: IllegalArgumentException: Cannot parse version '0.01.0' with '0Y.0M.MICRO'
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

I am trying to integrate jreleaser with my repo: https://github.com/p-marcin/java-dev-vm

With the following `jreleaser.yml`:
```yaml
project:
  versionPattern: CALVER:0Y.0M.MICRO

release:
  github:
    owner: p-marcin
    overwrite: true
    releaseName: '{{tagName}}'
    draft: true
    changelog:
      formatted: ALWAYS
      preset: conventional-commits
      format: '- {{commitShortHash}} {{commitTitle}}'
      categoryTitleFormat: '### {{categoryTitle}}'
      contributors:
        enabled: false
```

Run the command:
`jreleaser release -D=jreleaser.project.version=24.09.6 --dry-run --output-directory=target` 

Here is the output of my `git tag`:
```
v24.08.1
v24.08.2
v24.08.3
v24.09.1
v24.09.2
v24.09.3
v24.09.4
v24.09.5
```

### Expected Behaviour

Dry-run is completed without an exception.

### Actual Behaviour

Exception is thrown:
```
java.lang.IllegalArgumentException: Cannot parse version '0.01.0' with '0Y.0M.MICRO'
	at org.jreleaser.version.CalVer.of(CalVer.java:460)
	at org.jreleaser.version.CalVer.defaultOf(CalVer.java:466)
	at org.jreleaser.model.internal.util.VersionUtils.defaultVersion(VersionUtils.java:94)
	at org.jreleaser.sdk.git.ChangelogGenerator.defaultVersion(ChangelogGenerator.java:169)
	at org.jreleaser.sdk.git.ChangelogGenerator.resolveTags(ChangelogGenerator.java:209)
	at org.jreleaser.sdk.git.ChangelogGenerator.resolveCommits(ChangelogGenerator.java:308)
	at org.jreleaser.sdk.git.ChangelogGenerator.createChangelog(ChangelogGenerator.java:102)
	at org.jreleaser.sdk.git.ChangelogGenerator.generate(ChangelogGenerator.java:632)
	at org.jreleaser.sdk.git.ChangelogProvider.resolveChangelog(ChangelogProvider.java:121)
	at org.jreleaser.sdk.git.ChangelogProvider.getChangelog(ChangelogProvider.java:66)
	at org.jreleaser.sdk.github.GithubReleaser.generateReleaseNotes(GithubReleaser.java:104)
	at org.jreleaser.engine.changelog.Changelog.createChangelog(Changelog.java:38)
	at org.jreleaser.engine.release.ChangelogResolver.resolve(ChangelogResolver.java:53)
	at org.jreleaser.workflow.ChangelogWorkflowItem.doInvoke(ChangelogWorkflowItem.java:35)
	at org.jreleaser.workflow.AbstractWorkflowItem.lambda$invoke$0(AbstractWorkflowItem.java:43)
	at org.jreleaser.engine.hooks.HookExecutor.execute(HookExecutor.java:70)
	at org.jreleaser.workflow.AbstractWorkflowItem.invoke(AbstractWorkflowItem.java:43)
	at org.jreleaser.workflow.WorkflowImpl.doExecute(WorkflowImpl.java:129)
	at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:54)
	at org.jreleaser.cli.Release.doExecute(Release.java:385)
	at org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:90)
	at org.jreleaser.cli.Release.execute(Release.java:311)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:52)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at org.jreleaser.cli.Main.execute(Main.java:98)
	at org.jreleaser.cli.Main.run(Main.java:81)
	at org.jreleaser.cli.Main.main(Main.java:70)
```

Attaching: [trace.log](https://github.com/user-attachments/files/17080231/trace.log)

I also get the same exception when using: `versionPattern: CALVER:YY.0M.MICRO`

### Environment Information

- **Operating System**: Ubuntu
- **JReleaser Version:** 1.14.0
- **JDK Version:** 21.0.4 (Oracle Corporation 21.0.4+8-LTS-274)

### PR DESCRIPTION
**Pull request by p-marcin**
Fixes #1728

### Context
- Updates pattern to `"(0[0-9]|[1-9][0-9]|[1-9][0-9]{2})"` for `0Y`, so `00.01.0` is correctly parsed as CALVER version
- Updates pattern to `"([0-9]|[1-9][0-9]|[1-9][0-9]{2})"` for `YY`, so `0.01.0` is correctly parsed as CALVER version
- Updates default CALVER value to `00` for `0Y`
- Fixes exceptions:
  - `IllegalArgumentException: Cannot parse version '0.01.0' with '0Y.0M.MICRO'`
  - `IllegalArgumentException: Cannot parse version '0.01.0' with 'YY.0M.MICRO'`
- Changes in Tests:
  - Creates Parameterized Test for `CalVer#defaultOf`
  - Updates existing tests to check `0Y.0M.MICRO`/`0Y.MM.MICRO`/`YY.0M.MICRO`/`YY.MM.MICRO` formats
- Changes in Docs: jreleaser/jreleaser.github.io#79

### Checklist
- [x] [Review Contribution Guidelines](https://github.com/jreleaser/jreleaser/blob/master/CONTRIBUTING.adoc).
- [x] Make sure all contributed code can be distributed under the terms of the 
      [Apache License 2.0](https://github.com/jreleaser/jreleaser/blob/master/LICENSE), e.g. the code was written by 
      you or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Update [documentation](https://github.com/jreleaser/jreleaser.github.io) when applicable.

### CODE REVIEW

File: api/jreleaser-model-api/src/main/java/org/jreleaser/version/CalVer.java [hunk 1]
```diff
@@ -70,8 +70,8 @@ public class CalVer implements Version<CalVer> {
 
     static {
         PATTERNS.put(T_YEAR_LONG, "([2-9][0-9]{3})");
-        PATTERNS.put(T_YEAR_SHORT, "([1-9]|[1-9][0-9]|[1-9][0-9]{2})");
-        PATTERNS.put(T_YEAR_ZERO, "(0[1-9]|[1-9][0-9]|[1-9][0-9]{2})");
+        PATTERNS.put(T_YEAR_SHORT, "([0-9]|[1-9][0-9]|[1-9][0-9]{2})");
```
Comment (aalmiray) [inline api/jreleaser-model-api/src/main/java/org/jreleaser/version/CalVer.java:73]: Why does T_YEAR_SHORT need an update?

File: api/jreleaser-model-api/src/main/java/org/jreleaser/version/CalVer.java [hunk 2]
```diff
@@ -465,7 +465,7 @@ public static CalVer defaultOf(String format) {
 
         return of(format, format.replace(T_YEAR_LONG, "2000")
             .replace(T_YEAR_SHORT, "0")
-            .replace(T_YEAR_ZERO, "0")
+            .replace(T_YEAR_ZERO, "00")
```
Comment (aalmiray) [inline api/jreleaser-model-api/src/main/java/org/jreleaser/version/CalVer.java:468]: This will make the year `2000` be equal to `00` for both `0Y` and `YY`, right?

File: api/jreleaser-model-api/src/main/java/org/jreleaser/version/CalVer.java (hunk 1 above)
Comment (p-marcin) [reply api/jreleaser-model-api/src/main/java/org/jreleaser/version/CalVer.java:73]: Here `"0"` is passed, but it won't match `"([1-9]|[1-9][0-9]|[1-9][0-9]{2})"` pattern:
https://github.com/jreleaser/jreleaser/blob/7e909958b12823fe5cd9427cfde889fa496ee21c/api/jreleaser-model-api/src/main/java/org/jreleaser/version/CalVer.java#L467

File: api/jreleaser-model-api/src/main/java/org/jreleaser/version/CalVer.java (hunk 2 above)
Comment (p-marcin) [reply api/jreleaser-model-api/src/main/java/org/jreleaser/version/CalVer.java:468]: For `YY`, value `00` is invalid.

I added a test in `version_invalid` for that:
obraz

Comment (aalmiray) [reply api/jreleaser-model-api/src/main/java/org/jreleaser/version/CalVer.java:468]: I guess the year `2000` is special and should match both `0Y` and `YY` making `00` valid for both formats.

Comment (p-marcin) [reply api/jreleaser-model-api/src/main/java/org/jreleaser/version/CalVer.java:468]: If so, I can update the PR 🙂

Comment (p-marcin) [reply api/jreleaser-model-api/src/main/java/org/jreleaser/version/CalVer.java:468]: But I wonder, doesn't this look better if someone use `YY` format, to version like:
- `0`
- `1`
- `2`
- `3`
- (...)
- `24`

instead of:
- `00`
- `1`
- `2`
- `3`
- (...)
- `24`

?

And with `0Y` it would be:
- `00`
- `01`
- `02`
- `03`
- (...)
- `24`

Comment (aalmiray) [reply api/jreleaser-model-api/src/main/java/org/jreleaser/version/CalVer.java:468]: True. Let's keep `0` for `YY`. In which case, the PR needs no updates, right?

Comment (p-marcin) [reply api/jreleaser-model-api/src/main/java/org/jreleaser/version/CalVer.java:468]: Yes, correct. No update needed in this case

**Review by aalmiray — APPROVED** [review]

**Comment by aalmiray** [comment]
Thank you 😄
