### PR TITLE
feat(gradle): Fix access to Task.project at task execution time

### LINKED ISSUE #1992: [gradle] JReleaser does not work with the Gradle configuration cache
## Description

Running `./gradlew jreleaserDeploy` with Gradle 9.1.0 (configuration cache enabled) fails,
because `JReleaserDeployTask` still calls `Task.project` at execution time.

## Reproduction

```shell
git clone --depth=1 https://github.com/DanielLiu1123/template-gradle.git
cd template-gradle
./gradlew jreleaserDeploy --configuration-cache --stacktrace
```

Configuration cache is becoming something big. Do we have any plans to support it?

### PR DESCRIPTION
**Pull request by mhoffrog**
Fixes #1992

### Context
The Gradle Project instance object must not be accessed from task execution during Gradle build runtime phase.
This is violating Gradle configuration cache pre-requisites and it is currently raising a warning since this kind of access is deprecated and will run into an error with Gradle 10.

### Solution
* **Refactor**
  * Internal plugin architecture reworked to centralize Gradle project metadata capture and configuration, reducing direct Gradle API coupling.
  * Tasks now share a common base for consistent initialization, simplifying task configuration and logging.
  * Several task inputs/outputs were streamlined; environment task now always re-runs (up-to-date disabled) and environment display uses the task's project directory.
  * Adds a JReleaserGradleProjectCapture value object and refactors the plugin to use it instead of direct Gradle Project access; method signatures and task base classes were updated to accept/use the capture and centralize project property resolution.

### Recommendations to do
- Class `AbstractJReleaserTask` should be renamed to something like `AbstractJReleaserCommonOptionsTask` or `AbstractJReleaserCoreOptionsTask` since it is now inheriting from `AbstractJReleaserDefaultTask` as next in the tasks inheritance hierarchy.

### Checklist
- [x] [Review Contribution Guidelines](https://github.com/jreleaser/jreleaser/blob/master/CONTRIBUTING.adoc).
- [x] Make sure all contributed code can be distributed under the terms of the 
      [Apache License 2.0](https://github.com/jreleaser/jreleaser/blob/master/LICENSE), e.g. the code was written by 
      you or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Update [documentation](https://github.com/jreleaser/jreleaser.github.io) when applicable.

### CODE REVIEW

**Comment by mhoffrog** [comment]
Was created too early by accident - will close for now and create another one at a later stage. Sorry for the noise.

**Comment by aalmiray** [comment]
Alternatively, you could set the PR as draft if you still want to work on it.

**Comment by mhoffrog** [comment]
@aalmiray How can this be efficiently tested? I could not find any unit test in the code. Does the smoke-test workflow work and and does it cover the gradle plugin?

**Comment by aalmiray** [comment]
It will have to be manually tested for now. I'm afraid that the smoke tests had to be disabled because they never worked on Windows.

File: plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/JReleaserGradleProjectCapture.groovy [hunk 1]
```diff
@@ -0,0 +1,133 @@
...
+        ExtraPropertiesExtension extraPropertiesExtension = gradleProject.extensions.extraProperties
+        Set<String> extraPropertyKeys = extraPropertiesExtension?.properties?.keySet()
+        if (extraPropertyKeys) {
+            propertyKeys += extraPropertyKeys
+            propertyKeys = propertyKeys.toSet()
+        }
+        return propertyKeys
+    }
+
+    String getName() {
```
Comment (aalmiray) [inline plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/JReleaserGradleProjectCapture.groovy]: Most of these getters could be removed if the backing fields do not use the `private` visibility modifier

File: plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/JReleaserProjectConfigurer.groovy [hunk 2]
```diff
@@ -60,22 +41,31 @@ import static org.kordamp.gradle.util.StringUtils.isBlank
...
-        Provider<JReleaserLoggerService> loggerProvider = project.gradle.sharedServices
-            .registerIfAbsent('jreleaserLogger', JReleaserLoggerService.class) { BuildServiceSpec<JReleaserLoggerService.Params> spec ->
-                spec.parameters.console.set(new AnsiConsole(project, 'JRELEASER'))
-                spec.parameters.logLevel.set(project.gradle.startParameter.logLevel)
-                spec.parameters.outputDirectory.set(outputDirectory)
-            }
+    static Provider<JReleaserLoggerService> getJReleaserLoggerServiceProvider(Project gradleProject) {
+        Gradle gradle = gradleProject.gradle
+        Provider<Directory> outputDirectoryProvider = getJReleaserOutputDirectoryProvider(gradleProject)
+        return gradleProject.gradle.sharedServices.registerIfAbsent(
```
Comment (aalmiray) [inline plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/JReleaserProjectConfigurer.groovy]: Change to `return gradle.`

File: plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/JReleaserProjectConfigurer.groovy [hunk 3]
```diff
@@ -87,318 +77,32 @@ class JReleaserProjectConfigurer {
             }
         })
 
-        project.tasks.named(JReleaserConfigTask.NAME, JReleaserConfigTask,
```
Comment (aalmiray) [inline plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/JReleaserProjectConfigurer.groovy:90]: Where are all these removed tasks registered now?

**Review by aalmiray — CHANGES_REQUESTED** [review]

File: plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/JReleaserGradleProjectCapture.groovy (hunk 1 above)
Comment (mhoffrog) [reply plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/JReleaserGradleProjectCapture.groovy]: done.

File: plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/JReleaserProjectConfigurer.groovy (hunk 2 above)
Comment (mhoffrog) [reply plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/JReleaserProjectConfigurer.groovy]: done.

**Comment by aalmiray** [comment]
@mhoffrog thank you for the update. Yet, there's still one item to be resolved: previously registered tasks are now gone from `JReleaserProjectConfigurer`. Without those the plugin does pretty much nothing.

File: plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/JReleaserProjectConfigurer.groovy (hunk 3 above)
Comment (mhoffrog) [reply plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/JReleaserProjectConfigurer.groovy:90]: Those code places did not register but did lookup the tasks by name and type to perform initial task property configuration. That was a maintenance issue. Now this all happens in the cTors of the task classes.
The tasks all are registered within [JReleaserPlugin.registerTasks(Project project)](https://github.com/mavenplugins/jreleaser/blob/12a3bce73127cfc101d0d659f018135eea44456d/plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/JReleaserPlugin.groovy#L120). This registration is not touched by this PR.

**Comment by mhoffrog** [comment]
> @mhoffrog thank you for the update. Yet, there's still one item to be resolved: previously registered tasks are now gone > from `JReleaserProjectConfigurer`. Without those the plugin does pretty much nothing.

no, this is not correct - overlap of my answering - see my [answer above](https://github.com/jreleaser/jreleaser/pull/2078#discussion_r2892768374).

Tasks are still registered as expected.

**Comment by mhoffrog** [comment]
> It will have to be manually tested for now. I'm afraid that the smoke tests had to be disabled because they never worked on Windows.

@aalmiray Ok, then I will try to get the smoke tests working in my organization and maybe tweak the action to trigger them manually with a selection of particular jobs and for ubuntu only. That should be sufficient cover for those plugin changes.

Would like to understand:

1. There are two different GitHub tokens being used within smoke test:
  Do you know what kind of access is to be granted for each of these tokens?
    - `secrets.GITHUB_PAT_TOKEN`
    - `secrets.GITHUB_ACCESS_TOKEN`
2. What values must be configured for the following GitHub vars:
   - `vars.GRAAL_JAVA_VERSION`
    - `vars.JAVA_VERSION`
    - `vars.JAVA_DISTRO`
3. What is the structure and the (**neutralized**) content of `.github-secrets.tar.gpg`?
  This has to be adopted on my forked repo to get smoke-tests working I guess.

Many thanks for your great engagement!

**Comment by aalmiray** [comment]
> 1. There are two different GitHub tokens being used within smoke test:
> 
>   Do you know what kind of access is to be granted for each of these tokens?
> 
>     - `secrets.GITHUB_PAT_TOKEN`
> 
>     - `secrets.GITHUB_ACCESS_TOKEN`

I believe full repo access and discussions is all that's needed. 

> 2. What values must be configured for the following GitHub vars:
> 
>    - `vars.GRAAL_JAVA_VERSION`
> 
>     - `vars.JAVA_VERSION`
> 
>     - `vars.JAVA_DISTRO`

25
21
zulu


> 3. What is the structure and the (**neutralized**) content of `.github-secrets.tar.gpg`?

These are credentials needed to push artifacts to object storage in OCI (remote Gradle cache). It should be ignored in your case.

File: plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/JReleaserGradleProjectCapture.groovy [hunk 4]
```diff
@@ -0,0 +1,105 @@
...
+ *
+ * @author Markus Hoffrogge
+ * @since 1.24.0
+ */
+class JReleaserGradleProjectCapture implements Serializable {
+    final String group
+    final String version
+    final String name
+    final String description
+    final boolean isMultiProject;
```
Comment (aalmiray) [inline plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/JReleaserGradleProjectCapture.groovy]: Please remove `;`
Also, the name should be just `multiProject` to follow conventions

File: plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/tasks/AbstractJReleaserDefaultTask.groovy [hunk 5]
```diff
@@ -0,0 +1,85 @@
...
+        extension.convention(JReleaserProjectConfigurer.getJReleaserExtension(project))
+        Provider<JReleaserLoggerService> jloggerServiceProvider
+            = JReleaserProjectConfigurer.getJReleaserLoggerServiceProvider(project)
+        jlogger.convention(jloggerServiceProvider)
+        usesService(jloggerServiceProvider)
+        gradleProjectCapture.convention(JReleaserGradleProjectCapture.of(project))
+        projectDirectory.convention(project.layout.projectDirectory)
+        outputDirectory.convention(JReleaserProjectConfigurer.getJReleaserOutputDirectoryProvider(project))
+        // Use project.pluginManager.withPlugin() to defer the dependency configuration until the plugin is actually applied
+        project.pluginManager.withPlugin('distribution') {
```
Comment (aalmiray) [inline plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/tasks/AbstractJReleaserDefaultTask.groovy:80]: Not every subtask requires this. It should be conditional.

**Review by aalmiray — CHANGES_REQUESTED** [review]

File: plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/tasks/AbstractJReleaserDefaultTask.groovy (hunk 5 above)
Comment (mhoffrog) [reply plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/tasks/AbstractJReleaserDefaultTask.groovy:80]: Did remove from `AbstractJReleaserDefaultTask.groovy` cTor to dedicate method `dependOnAssembleDistIfDistributionPluginIsApplied()` in this class.

The following 10 tasks did have been configured for assembleDist dependency before:
- JReleaserAnnounceTask.groovy
- JReleaserChecksumTask.groovy
- JReleaserConfigTask.groovy
- JReleaserFullReleaseTask.groovy
- JReleaserPackageTask.groovy
- JReleaserPrepareTask.groovy
- JReleaserPublishTask.groovy
- JReleaserReleaseTask.groovy
- JReleaserSignTask.groovy
- JReleaserUploadTask.groovy

These now call `dependOnAssembleDistIfDistributionPluginIsApplied()`.

File: plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/JReleaserGradleProjectCapture.groovy (hunk 4 above)
Comment (mhoffrog) [reply plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/JReleaserGradleProjectCapture.groovy]: done.

**Comment by mhoffrog** [comment]
@aalmiray Did find another issue from testing - will update, when done.

**Comment by mhoffrog** [comment]
@aalmiray Please perform another review. Did apply the following changes:

- JReleaserGradleProjectCapture.groovy:
  - filter properties that would raise a deprecation warning
  - implement debug level logs about how each property
    key is being processed

- AbstractJReleaserDefaultTask.groovy:
  - add method logClassLoaderURLs()

- JReleaserEnvTask.groovy:
  - add option --logClasspath
    - default: false
    - call logClassLoaderURLs() if option is set

Smoke test fully succeeded now.

The remaining Gradle deprecation warnings logged by JReleaserEnv task case are initiated by kordamp plugins only.

See [jr_smoketest_logs_20260310.zip/6_Gradle ubuntu-latest.txt](https://github.com/user-attachments/files/25855559/jr_smoketest_logs_20260310.zip)

File: plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/JReleaserGradleProjectCapture.groovy [hunk 6]
```diff
@@ -0,0 +1,137 @@
...
+class JReleaserGradleProjectCapture implements Serializable {
+    final String group
+    final String version
+    final String name
+    final String description
+    final boolean multiProject
+    final String javaApplicationMainClass
+    final String javaApplicationMainModule
+
+    private final Map<String, Object> properties
```
Comment (aalmiray) [inline plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/JReleaserGradleProjectCapture.groovy]: It bothers me a little that the enclosing class has to be declared as Serializable but this field breaks the invariants as `Object` is not serializable, right?

File: plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/JReleaserGradleProjectCapture.groovy [hunk 7]
```diff
@@ -0,0 +1,137 @@
...
+            }
+        }
+        return projectProperties
+    }
+
+    private static Set<String> collectGradleProjectPropertyKeys(Project gradleProject) {
+        Set<String> propertyKeys = gradleProject.properties.keySet()
+        ExtraPropertiesExtension extraPropertiesExtension = gradleProject.extensions.extraProperties
+        Set<String> extraPropertyKeys = extraPropertiesExtension?.properties?.keySet()
+        //System.out.println("### extraPropertyKeys: ${extraPropertyKeys}")
```
Comment (aalmiray) [inline plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/JReleaserGradleProjectCapture.groovy]: Please remove this commented line

File: plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/tasks/AbstractJReleaserDefaultTask.groovy [hunk 8]
```diff
@@ -0,0 +1,100 @@
...
+        }
+    }
+
+    // For analysis purposes, JReleaserEnvTask has an option implemented to perform it at task execution time.
+    void logClassLoaderURLs() {
+        URLClassLoader classLoader = (URLClassLoader) this.getClass().getClassLoader()
+        JReleaserLogger logger = jlogger.get().logger
+        List<URL> urls = Arrays.asList(classLoader.getURLs())
+        String taskName = this.getClass().simpleName.replace('_Decorated', '')
+        logger.info("====== Task '{}' classLoader URLs[{}] - BEGIN ======", taskName, urls.size())
```
Comment (aalmiray) [inline plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/tasks/AbstractJReleaserDefaultTask.groovy:95]: This should probably be set to debug

File: plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/tasks/JReleaserConfigTask.groovy [hunk 9]
```diff
@@ -74,9 +74,11 @@ abstract class JReleaserConfigTask extends AbstractPlatformAwareJReleaserTask {
         deploy = objects.property(Boolean).convention(false)
         download = objects.property(Boolean).convention(false)
         command = JReleaserCommand.CONFIG
+        dependOnAssembleDistIfDistributionPluginIsApplied()
 
         // Disable up-to-date checks: jreleaser/issues/1972
         this.outputs.upToDateWhen { false }
+
```
Comment (aalmiray) [inline plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/tasks/JReleaserConfigTask.groovy]: Please remove empty line

File: plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/tasks/JReleaserEnvTask.groovy [hunk 10]
```diff
@@ -39,32 +36,38 @@ import javax.inject.Inject
...
     @TaskAction
     void performAction() {
-        Environment.display(jlogger.get(), basedir.get().asFile.toPath(),
+        if (logClasspath.getOrElse(false)) {
+            logClassLoaderURLs()
+        }
+        Environment.display(jlogger.get().logger, projectDirectory.get().asFile.toPath(),
             settings.present ? settings.get().asFile.toPath() : null)
     }
+
```
Comment (aalmiray) [inline plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/tasks/JReleaserEnvTask.groovy]: Please remove empty line

**Review by aalmiray — CHANGES_REQUESTED** [review]

**Comment by aalmiray** [comment]
Thank you for your contributions, and your patience.

File: plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/tasks/AbstractJReleaserDefaultTask.groovy (hunk 8 above)
Comment (mhoffrog) [reply plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/tasks/AbstractJReleaserDefaultTask.groovy:95]: @aalmiray I thought about that but came to conclusion to leave it as info, since this has to be explicitly enabled by an option - currently in the JReleaserEnvTask only. In this case I would expect to get it without being forced to enable debug level in addition - that maybe irritating. Also debug outputs will somewhat "hide" the output beyond all the others.

What do you think?

File: plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/tasks/JReleaserEnvTask.groovy (hunk 10 above)
Comment (mhoffrog) [reply plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/tasks/JReleaserEnvTask.groovy]: done.

File: plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/tasks/JReleaserConfigTask.groovy (hunk 9 above)
Comment (mhoffrog) [reply plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/tasks/JReleaserConfigTask.groovy]: done.

File: plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/JReleaserGradleProjectCapture.groovy (hunk 7 above)
Comment (mhoffrog) [reply plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/JReleaserGradleProjectCapture.groovy]: done.

File: plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/JReleaserGradleProjectCapture.groovy (hunk 6 above)
Comment (mhoffrog) [reply plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/JReleaserGradleProjectCapture.groovy]: Refactored to `Map<String, Serializable>`.

**Comment by mhoffrog** [comment]
> Thank you for your contributions, and your patience.

No worries - patience is my favorite...

Smoke tests succeeded: [jr_smoketest_logs_20260313.zip](https://github.com/user-attachments/files/25966144/jr_smoketest_logs_20260313.zip) - see `jr_smoketest_logs_20260313.zip\Gradle ubuntu-latest\10_JReleaser.txt` inside.

**Comment by mhoffrog** [comment]
@aalmiray  Did re-base to current main and did a few intermediate force pushes to leverage review of the most recent changes - just click on most recent [compare](https://github.com/jreleaser/jreleaser/compare/d7347f371bb29bfc8a6056ccdd0e73bc119e8374..0305213d712e864773816387f2c800b659a5461c).

**Review by aalmiray — APPROVED** [review]

**Comment by mhoffrog** [comment]
Many thanks for your approval!
If there is anything else to do from my end please let me know.

**Comment by aalmiray** [comment]
Thank you 😄

**Comment by aalmiray** [comment]
I think you have a relationship with OneDev, isn't it? We're considering adding support for it #2057. 

How's your xp with the platform so far?

**Comment by mhoffrog** [comment]
Long time ago I did have a look into OneDev regarding its Web interface but I did never use it actually as a CI/CD framework.

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.24.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.24.0))
