### PR TITLE
Fix cosign-support by verifying against err-output

### LINKED ISSUE #835: Cosign verify not working
### Steps to Reproduce

Add the following configuration to **jreleaser.yml**

```
signing:
  active: ALWAYS
  enabled: true
  armored: true
  mode: cosign
  cosign:
    version: 1.8.0
    privateKeyFile: cosign.key
    publicKeyFile: cosign.pub
```

Under both Linux (inside a GitHub-action) and on MacOS X (x86) you will see that jreleaser is downloading cosign in the
correct version but fails to verify it.

The reason is that jreleaser validates the version against stdout while cosign is reporting its version via err-out.

This makes cosign currently unusable with jreleaser.

I have already prepared a fix and will provide a PR shortly :)

### Environment Information

- **Operating System**: Linux and OSX
- **JReleaser Version:** 1.0.0
- **JDK Version:** 11 and 17

### PR DESCRIPTION
**Pull request by codepitbull**
Fixes #835

### Context

DownloadableTool should be able to also verify the err-output.
In the concrete case cosign is reporting its version via the error-channel, resulting in verify to always fail.

### Checklist
- [x] [Review Contribution Guidelines](https://github.com/jreleaser/jreleaser/blob/master/CONTRIBUTING.adoc).
- [x] Make sure all contributed code can be distributed under the terms of the 
      [Apache License 2.0](https://github.com/jreleaser/jreleaser/blob/master/LICENSE), e.g. the code was written by 
      you or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Update [documentation](https://github.com/jreleaser/jreleaser.github.io) when applicable.

### CODE REVIEW

File: sdks/tool-sdk/src/main/java/org/jreleaser/sdk/tool/AbstractTool.java [hunk 1]
```diff
@@ -32,12 +32,14 @@ public class AbstractTool {
     protected final JReleaserContext context;
     protected final DownloadableTool tool;
     protected final String name;
+    protected final boolean verifyErrorOutput;
 
-    public AbstractTool(JReleaserContext context, String name, String version) {
+    public AbstractTool(JReleaserContext context, String name, String version, boolean verifyErrorOutput) {
```
Comment (aalmiray) [inline sdks/tool-sdk/src/main/java/org/jreleaser/sdk/tool/AbstractTool.java:37]: Please add an overloaded constructor with the last boolean flag set to `false` as default. This would allow the `Upx.java` tool to remain unchanged.

**Review by aalmiray — CHANGES_REQUESTED** [review]

File: sdks/tool-sdk/src/main/java/org/jreleaser/sdk/tool/AbstractTool.java (hunk 1 above)
Comment (codepitbull) [reply sdks/tool-sdk/src/main/java/org/jreleaser/sdk/tool/AbstractTool.java:41]: Done :)

**Comment by aalmiray** [comment]
Thank you for the PR! 😄 

Note that I've squashed your changes to comply with conventional commits as explained at https://github.com/jreleaser/jreleaser/blob/main/CONTRIBUTING.adoc
