### PR TITLE
fix: correct JSON syntax in init template

### LINKED ISSUE #1814: Syntax error in the Jreleaser JSON configuration generated by gradle plugin
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone my [project](https://github.com/chains-project/maven-module-graph/) and checkout to branch [`jreleaser`](https://github.com/chains-project/maven-module-graph/tree/jreleaser). 
2. Run `./gradlew jreleaserInit --format json --overwrite`.
3. Expect `jreleaser.json` to created at the root directory.

### Expected Behaviour

`:` after `"languages"` and `,` before `"inceptionYear"` should be present.

```json
...
    "languages": {
        "java": {
          "groupId": "com.acme",
          "version": "8"
        },
    },
    "inceptionYear": "2025"
  },

...
```

### Actual Behaviour

`:` and `,` are abset

```json
...
    "languages" { //missing
        "java": {
          "groupId": "com.acme",
          "version": "8"
        },
    } // missing
    "inceptionYear": "2025"
  },
...
```

### Environment Information

- **Operating System**: 22.04.1-Ubuntu
- **JReleaser Version:** 1.16.0
- **JDK Version:** 17.0.10 OpenJDK

### PR DESCRIPTION
**Pull request by algomaster99**
Fixes #1814 

### Context

Fixes the JSON syntax in template.

### Checklist
- [x] [Review Contribution Guidelines](https://github.com/jreleaser/jreleaser/blob/master/CONTRIBUTING.adoc).
- [x] Make sure all contributed code can be distributed under the terms of the 
      [Apache License 2.0](https://github.com/jreleaser/jreleaser/blob/master/LICENSE), e.g. the code was written by 
      you or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Update [documentation](https://github.com/jreleaser/jreleaser.github.io) when applicable.

### CODE REVIEW

**Comment by algomaster99** [comment]
Not sure where I should test. My first choice was `org.jreleaser.config.json.JsonJReleaserConfigParserTest` but that checks already built configuration files.

I have created `org.jreleaser.engine.init.InitTest` that has a single test right now but it fails with `java.lang.IllegalArgumentException: Unsupported file format. Must be one of []`. 

Two questions:
1. Where should I add the test?
2. Why is the exception thrown and the list is empty?

File: core/jreleaser-engine/src/test/java/org/jreleaser/engine/init/InitTest.java [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
+
+public class InitTest {
+    @Test
+    void jsonSyntaxIsCorrect(@TempDir Path outputDirectory) {
+        // given:
+        String format = "json";
+
+        // when:
+        Init.execute(null, format, false, outputDirectory);
```
Comment (aalmiray) [inline core/jreleaser-engine/src/test/java/org/jreleaser/engine/init/InitTest.java:19]: Do not pass `null` as first argument. Rather use an existing implementation. I believe there's one used by SDK projects.

**Review by aalmiray — CHANGES_REQUESTED** [review]

**Comment by aalmiray** [comment]
The empty list is caused by no service providers available in testing. You'll have to configure the `jreleaser-config-json` module in `jreleaser-engine.gradle` using the the `testRuntime` scope.

**Comment by algomaster99** [comment]
@aalmiray CI is green. Can be merged :)

**Comment by aalmiray** [comment]
Thank you for the PR!

**Comment by algomaster99** [comment]
No problem. Thanks for your help! 😁
